### ISSUE TITLE
Could not find command "server".

### ISSUE THREAD

**Issue by GCorbel** [uplus/solargraph-utils.py#4]
I try to use solargraph with deoplete, with [depolete-solargraph](https://github.com/uplus/deoplete-solargraph). When I launch an autocompletion, I have this message : 
```
Traceback (most recent call last):
^@  File "/home/dougui/.vim/bundle/deoplete-solargraph/rplugin/python3/deoplete/source/solargraph.py", line 56, in start_server
^@    self.server = solar.Server()
^@  File "/home/dougui/.local/lib/python3.6/site-packages/solargraph_utils/core.py", line 19, in __init__
^@    self.start()
^@  File "/home/dougui/.local/lib/python3.6/site-packages/solargraph_utils/core.py", line 42, in start
^@    raise ServerError('Failed to startserver' + (output and ':\n' + output))
^@solargraph_utils.helpers.ServerError: Failed to start server:
^@Could not find command "server".
```

**Comment by megalithic** [comment]
Same here; just installed/setup, using the solargraph gem at 0.18.0 per another solargraph issue. @uplus any suggestions?

**Comment by uplus** [comment]
solargraph removed `server` subcommand.
because it supported language-server-protocol.

Neovim has LSP Client.
I am thinking about migrating to LSP-Client by deprecating this plugin.

https://github.com/autozimu/LanguageClient-neovim
